### ISSUE TITLE
From Assembly to chromosome bins

### ISSUE THREAD

**Issue by mictadlo** [mdozmorov/HiC_tools#1]
Hi, 
We have a denovo plant genome assembly and HiC data but without any annotation. We would like to get 19 chromosome bins (19 FASTA files).

Which tool could work for us?

Thank you in advance,

Michal

**Comment by mdozmorov** [comment]
More tools for de novo genome assembly from Hi-C reads: https://omictools.com/assembly-scaffolding-1-category
