### ISSUE TITLE
A new Hi-C scaffolder: HapHiC

### ISSUE THREAD

**Issue by zengxiaofei** [mdozmorov/HiC_tools#17]
Dear Professor Dozmorov,

We are pleased to introduce our new Hi-C scaffolder, HapHiC.

HapHiC exhibits superior performance in handling haplotype-resolved assemblies without the need for reference genomes. This scaffolding tool supports various ploidy levels and has been successfully validated across diverse taxa. This study also provides new insights into the challenges in allele-aware scaffolding, comparing it with other scaffolders such as ALLHiC, YaHS, 3D-DNA, LACHESIS, and SALSA2 through comprehensive analyses on various adverse factors.

GitHub: https://github.com/zengxiaofei/HapHiC
Article: [Chromosome-level scaffolding of haplotype-resolved assemblies using Hi-C data without reference genomes](https://doi.org/10.1038/s41477-024-01755-3)
Research Briefing: [Achieving de novo scaffolding of chromosome-level haplotypes using Hi-C data](https://doi.org/10.1038/s41477-024-01756-2)

Best regards,
Xiaofei

**Comment by mdozmorov** [comment]
Hi Xiaofei, our library is slow in providing access, I'm reading the preprint. Interesting work, would you like to make a pull request? I can just add your description but a PR would be a better attribution.

**Comment by zengxiaofei** [comment]
Thank you very much! I have made a pull request.

**Comment by mdozmorov** [comment]
This is excellent, thank you!
