### ISSUE TITLE
please move cLoops from TAD caller to loop caller (significant interaction caller)

### ISSUE THREAD

**Issue by YaqiangCao** [mdozmorov/HiC_tools#3]

**Comment by mdozmorov** [comment]
Thanks, @YaqiangCao, done. Not sure how it ended in the wrong place, nightly errors :)

**Comment by YaqiangCao** [comment]
Hi Mdozmorov/Hic_tools,
    Thanks for list cLoops in your repo~
Best regards,
Yaqiang
